### ISSUE TITLE
besides Elementor templates

### ISSUE THREAD

**Issue by mohammadr3z** [dinhtungdu/custom-elementor-library-dummy-api#1]
Hello
What do I do if I want to add my own templates besides Elementor templates?

**Comment by mohammadr3z** [comment]
@dinhtungdu

**Comment by dinhtungdu** [comment]
Hi @mohammadr3z, I'm sorry for the super late reply, I forgot to Watch this repo 😅

The method I mentioned in the [blog](https://dinhtungdu.github.io/create-your-own-elementor-template-library/) replaces the Elementor remote library, so you can't display the Elemtor templates with your ones.

There is a workaround here is merging the Elementor library with your own (copying Elementor library data to your library JSON data), but you will need to keep it up to date with Elementor. Besides, you need to copy Elementor templates data (free ones only) to your server so the customer can import them.

Hope this help! :)

**Comment by mohammadr3z** [comment]
Thank you very much for the answer @dinhtungdu 
But what do you do here?
https://github.com/elementor/elementor/issues/5860#issuecomment-427618068

**Comment by dinhtungdu** [comment]
@mohammadr3z I tried to submit a PR to Elementor that allows theme or other plugin filters the template data URL based on the template id, so we can append our template data to Elementor library and insert them without replacing the remote source (as I did in the article). But they didn't accept it.

**Comment by mohammadr3z** [comment]
@dinhtungdu So you have an example code to do this?
Like JetElements plugin ready templates or JupiterX templates that add their own ready made templates along with elementor templates.
Thank you for your help.

**Comment by dinhtungdu** [comment]
@mohammadr3z the code example is already on the issue page: this https://github.com/elementor/elementor/issues/5860#issuecomment-427618068 and this https://github.com/elementor/elementor/issues/5860#issuecomment-475035672.

I don't know about JupiterX, but what JetElement does is writing its own library without using the one from Elementor (but it's similar to Elementor), it's a lot of work. I don't have any experience on backbone so I didn't go with that approach. Also, we didn't have enough resource to do it at that time 😅.

**Comment by mohammadr3z** [comment]
@dinhtungdu Thank you very much for your time

**Comment by dinhtungdu** [comment]
@mohammadr3z You're welcome. If you really need to keep Elementor library, the best way to make one. You can examine the source code of Elementor and JetElements. Maybe you will find it easier than I thought :)
